services:
  ewm-db:
    image: postgres:16.1
    container_name: postgres-main-db
    ports:
      - "6543:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

  stats-db:
    image: postgres:16.1
    container_name: postgres-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=stats

  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: "bash -c \
                'kafka-topics --create --topic stats.user-actions.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
                kafka-topics --create --topic stats.events-similarity.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092'"
    init: true

#  stats-server:
#    build: stats/stats-server
#    container_name: stats-server
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
#      - SPRING_DATASOURCE_USERNAME=stat
#      - SPRING_DATASOURCE_PASSWORD=stat
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

#  comment-service:
#    build: core/comment-service
#    container_name: comment-service
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/comment_db
#      - SPRING_DATASOURCE_USERNAME=comment_user
#      - SPRING_DATASOURCE_PASSWORD=password1
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

#  event-service:
#    build: core/event-service
#    container_name: event-service
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/event_db
#      - SPRING_DATASOURCE_USERNAME=event_user
#      - SPRING_DATASOURCE_PASSWORD=password2
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

#  request-service:
#    build: core/request-service
#    container_name: request-service
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/request_db
#      - SPRING_DATASOURCE_USERNAME=request_user
#      - SPRING_DATASOURCE_PASSWORD=password3
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

#  user-service:
#    build: core/user-service
#    container_name: user-service
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/user_db
#      - SPRING_DATASOURCE_USERNAME=user_user
#      - SPRING_DATASOURCE_PASSWORD=password4
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

#  config-server:
#    build: infra/config-server
#    container_name: config-server
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

#  discovery-server:
#    build: infra/discovery-server
#    container_name: discovery-server
#    ports:
#      - "8761:8761"
#    environment:
#      - EUREKA_INSTANCE_HOSTNAME=discovery-server

#  gateway-server:
#    build: infra/gateway-server
#    container_name: gateway-server
#    ports:
#      - "8080:8080"
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka